openapi: 3.0.0
info:
  title: "NC Sample REST API"
  description: "REST API with some extremely useless endpoints"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Doughnut:
      type: object
      required:
        - doughnut_id
        - doughnut_type
        - price
        - calories
        - contains_nuts
      properties:
        doughnut_id:
          type: integer
        doughnut_type:
          type: string
        price: 
          type: number
        calories:
          type: number
        contains_nuts: 
          type: boolean

  parameters:
    DoughnutParam:
      in: path 
      name: doughnut_id
      required: true
      schema: 
        type: integer
        minimum: 1
      description: "The Doughnut Id"


paths:
  /healthcheck:
    get:
      operationId: "app.get_healthcheck"
      tags:
        - "Healthcheck"
      summary: "Simple healthcheck"
      responses:
        "200":
          description: "Application is healthy"
  /doughnuts:
    get:
      operationId: "app.get_doughnuts"
      tags:
        - "Doughnuts"
      summary: "Get the list of all Doughnuts"
      responses:
        "200":
          description: "Successfully read Doughnuts"
        "404":
          description: "No doughnuts"
        "500":
          description: "Unexpected exception"
  /doughnuts/{doughnut_id}: 
    get:
      parameters:
        - $ref: '#/components/parameters/DoughnutParam'
      operationId: "app.get_doughnut"
      tags:
        - "Doughnut"
      summary: "Get details of single doughnut"
      responses:
        "200":
          description: "Successfully read Doughnut details"
        "404":
          description: "No such doughnut"
        "500":
          description: "Unexpected exception"
  